# https://circleci.com/docs/docker
version: 2
jobs:
  build:
    docker:
      - image: jumanjiman/cci:20170430T2312-git-3c95863

    working_directory: ~/wtf/

    steps:
      - setup_remote_docker

      - checkout

      - run:
          name: Store variables
          command: |
            cat > /tmp/vars <<-EOF
            export VERSION=1.11.82
            export BUILD_DATE=$(date +%Y%m%dT%H%M)
            export VCS_REF=${CIRCLE_SHA1:0:7}
            export TAG=\${VERSION}-\${BUILD_DATE}-git-\${VCS_REF}
            EOF

      - run:
          name: Show details of build environment
          command: |
            set -x
            . /tmp/vars
            env | grep -e BUILD_DATE -e VCS_REF -e VERSION -e TAG
            docker info
            docker version
            env | grep CIRCLE

      - run:
          name: Build the image
          command: |
            . /tmp/vars
            make all

      - run:
          name: View image details
          command: |
            docker images
            docker inspect jumanjiman/aws

      - run:
          name: Test the image
          command: |
            . /tmp/vars
            make test

      - deploy:
          name: Deploy from master branch
          command: |
            if [[ ${CIRCLE_BRANCH} = master ]] && [[ -z ${CIRCLE_PR_NUMBER} ]]; then
              . /tmp/vars
              docker login -u ${user} -p ${pass}
              docker tag jumanjiman/aws jumanjiman/aws:${TAG}
              docker push jumanjiman/aws:${TAG}
              docker push jumanjiman/aws:latest
              docker logout
              curl -X POST 'https://hooks.microbadger.com/images/jumanjiman/aws/Lan3ZPTzecbxGrzvkdxR-dTxIB8='
            fi
